#!/bin/env node

var args = process.argv.splice(2);
var config = require('./configuration');

if (args[0] == 'start') {
  require('./web');
}
else if (args[0] == 'db') {
  require('./spider').crawl(config().schoolID);
}
else if (args[0] == 'plugins') {
  console.log('Most of the plugins are in a private repo of mine, but when you want to set those up and you have the login creditentials make sure to do this:');
  console.log('git submodule init');
  console.log('git submodule sync');
  console.log('git submodule update');
  console.log('After that, make sure to install deps for the plugins in their respective directories under ./plugins');
}
else {
  console.log('rooster.io commandline util:');
  console.log('commands:');
  console.log('rooster start\t\t--\tStarts rooster.io from the commandline');
  console.log('rooster db\t\t--\tInitializes the database with the students and stuff from the schoolID specified in the settings.json');
  console.log('rooster plugins\t\t--\tShows help to setup plugins');
  console.log('rooster help\t\t--\tShows this menu');
}
